---
- hosts: all
  become: yes
  name: NGINX
  tasks: 
    - name: Update apt and install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
        
    - name: Start nginx 
      service:
        name: nginx
        state: started