---
- hosts: all
  become: yes
  name: NODEJS & PM2
  tasks: 
    - name: Add NodeJS apt source
      shell: 
        cmd: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install NodeJS
      apt:
        name: nodejs
        state: present
    - name: Install pm2
      npm: 
        name: pm2
        global: yes
    